### ISSUE TITLE
您好，方便提供您CMED数据集最终结果的checkpoint模型文件吗？ 我有急用

### ISSUE THREAD

**Issue by liqijiaLQJ** [longlongman/CasRel-pytorch-reimplement#4]

**Comment by longlongman** [comment]
你好，我测试完结果就删除了checkpoint文件，没有办法提供，不过CMED训练起来挺快的，你可以重新训练一个。

**Comment by liqijiaLQJ** [comment]
> 你好，我测试完结果就删除了checkpoint文件，没有办法提供，不过CMED训练起来挺快的，你可以重新训练一个。
好的，感谢！

**Comment by liqijiaLQJ** [comment]
> 你好，我测试完结果就删除了checkpoint文件，没有办法提供，不过CMED训练起来挺快的，你可以重新训练一个。

好的，感谢！

**Comment by wenwenweny** [comment]
你好，checkpoint文件生成了吗，方便提供一下吗？

**Comment by liqijiaLQJ** [comment]
> 你好，checkpoint文件生成了吗，方便提供一下吗？

抱歉 我把代码修改成适应其他任务了  可能不再方便用于CEMD数据集了   但是训练起来很快  不太占用显存空间  您可以自己训练一下

**Comment by wenwenweny** [comment]
好的，麻烦问一下哪个py是训练得到checkpoint/CMED的文件，新手小白，直接运行train.py报错系统找不到指定的路径。: 'C:/Users/Administrator/Desktop/CasRel-pytorch-reimplement-master/checkpoint/CMED'

**Comment by wenwenweny** [comment]
好的

**Comment by wenwenweny** [comment]
好的，谢谢
