### ISSUE TITLE
环境配置&expected backend CUDA and dtype Float but got backend CUDA and dtype Long

### ISSUE THREAD

**Issue by Genjiz** [longlongman/CasRel-pytorch-reimplement#8]
我想请问一下您的cuda版本，pytorch版本，cudavision版本是什么？因为casrel本身的环境配置是tensorflow1.13.1，那么对应的cuda就是10.0，但是pytorch只有1.2以下是对应cuda10.0的，往上的版本都是对应9或者10.1，我现在运行代码的时候遇到一个问题：expected backend CUDA and dtype Float but got backend CUDA and dtype Long，网上搜到的可能的解决方法是把pytorch由1.2改为1.3，但是这样对应的cuda,tensorflow都要更改版本，所以想知道问题可能出在哪里？

**Comment by Genjiz** [comment]
不好意思，刚刚上面提到的cudavision说错了，应该是torchvision

**Comment by longlongman** [comment]
cuda 10.1, pytorch 1.4, torchvision无

**Comment by Genjiz** [comment]
> cuda 10.1, pytorch 1.4, torchvision无

请问您是如何做到cuda10.1 tensorflow-gpu 1.13.1而不报dll错误的呢

**Comment by Genjiz** [comment]
已解决，我本来用的cudatoolkit，conda会检测cudatoolkit与tensorflow的冲突而不让安装，用pip安装会报dll错误，在官网下载cuda10.1之后，用conda可以安装tensorflow1.13.1并且不会报dll错误，用pip安装还是会有dll这个错误，这个应该是pip自身的问题。假如是用pip安装tensorflow1.13.1，还有一种解决方法是修改cuda或者cudatoolkit的三个dll文件名（但是如果修改的是cudatoolkit里的文件名的话，电脑也必须已经安装了官网的cuda，这里不知道到底差在哪里）
